config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords"}
  
	resources :users, only: [ :show] 
	resources :potential_users, only: [ :show]
  
	root 'static_pages#home'
	resources :conversations, only: [:create, :show] 
  
	resources :conversations do #ici ça génère trop de lignes
		resources :posts, only: [:create]
		resources :calls, only: [:create]
	end	
  
	resources :posts, only: [:update, :edit]
	
	post 'posts/:id/support' => 'posts#support'
	delete 'posts/:id/remove' => 'posts#remove'
	post 'posts/:id/unsupport' => 'posts#unsupport' 
	#post 'posts/:id/hide' => 'posts#hide'
  
	post 'calls/:id/support' => 'calls#support'
	delete 'calls/:id/remove' => 'calls#remove'
	post 'calls/:id/unsupport' => 'calls#unsupport'
	post 'calls/:id/decline' => 'calls#decline'
  
  
	post 'profiles/attach_to_user' => 'profiles#attach_to_user' 
	post 'profiles/detach_from_user' => 'profiles#detach_from_user'
	
	resources :facebooks do #ici ça génère trop de lignes
		resources :facebook_activations, only: [:new, :create]
		get "/facebook_activations/:id/report_page" => 'facebook_activations#report_page' 
		post "/facebook_activations/:id/report_as_abusive" => 'facebook_activations#report_as_abusive'
	end
  
	get "/facebooks/:facebook_id/facebook_activations/validate" => 'facebook_activations#validate' 
  
	post "/facebook_activations/:id/resend" => 'facebook_activations#resend' 
	delete "/facebook_activations/:id/cancel" => 'facebook_activations#cancel' 
  
  	resources :twitters do #ici ça génère trop de lignes
		resources :twitter_activations, only: [:new]
	end
	get "/twitters/:twitter_id/twitter_activations/validate" => 'twitter_activations#validate' 
	get "/twitters/:twitter_id/twitter_activations/fail" => 'twitter_activations#fail'
	
	resources :websites do #ici ça génère trop de lignes
		resources :website_activations, only: [:new]
	end
	get "/websites/:website_id/website_activations/validate" => 'website_activations#validate' 
	get "/websites/:website_id/website_activations/fail" => 'website_activations#fail'

end

app/models/user.rb
class User < ActiveRecord::Base
	# DEVISE
	devise 	:database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
	validates :name, presence: true
	validates_uniqueness_of :name, :case_sensitive => false, :message => "This name has already been taken"
	
	# PROFILE Management	
	Profile::PROFILE_TYPES.each do |x|
		eval("has_many :"+Profile::PROFILE_NAME_PLURAL[x]+", as: :owner, class_name: "+x)
	end
	
	def profiles 
		code_string = Profile::PROFILE_TYPES.collect{|x| "self."+Profile::PROFILE_NAME_PLURAL[x]}
		code_string = code_string.join(" + ")
		return eval(code_string)
	end
			
	def can_post?(conversation)
		return true
	end
	
	def can_call?(conversation)
		return conversation.persisted?
	end
		
	#if call has given a post or child calls, the s/u have been switched to the post. the call can't be s/u anymore
	def can_s_call?(call)
		return call.callable != self && !call.supporters.include?(self) && call.status == "active" && !call.declined && call.post.nil?
	end
	def can_u_call?(call)
		return call.callable != self && !call.unsupporters.include?(self) && call.status == "active" && !call.declined && call.post.nil?
	end
	def can_remove_s_or_u_call?(call)
		return call.callable != self && (call.supporters.include?(self) || call.unsupporters.include?(self)) && !call.declined && call.post.nil? && call.status == "active"
	end
	
	def can_answer_call?(call)
		return call.callable == self && call.post.nil? && call.status == "active" && !call.declined
	end	
	
	def can_edit_post?(post)
		return post.creator == self  
	end
	
	def can_s_post?(post)
		return !post.supporters.include?(self) && post.status == "active"
	end
	def can_u_post?(post)
		return post.creator != self && !post.unsupporters.include?(self) && post.status == "active"
	end
	def can_remove_s_or_u_post?(post)
		return (post.supporters.include?(self) || post.unsupporters.include?(self)) && post.status == "active"
	end
	
	def supports(object)
		oa = ObjectAction.find_or_initialize_by(creator: self, object: object)
		oa.support = "up"
		oa.status = "active"
		oa.save!
	end
	
	def unsupports(object)
		oa = ObjectAction.find_or_initialize_by(creator: self, object: object)
		oa.support = "down"
		oa.status = "active"
		oa.save!
	end
	
	def remove(object)
		oa = ObjectAction.find_by(creator: self, object: object)
		oa.status = "removed"
		oa.save!
	end


	
	# CALL Management
	#CALL S/U
	has_many :object_actions, inverse_of: :creator
	#has_many :callouts, through: :object_actions, source: :object, source_type: 'Call', foreign_key: "object_id"

	def callouts
		return Call.select{|x| x.supporters.include?(self) || x.unsupporters.include?(self)}
	end
	has_many :callins, as: :callable, class_name: "Call"

	# POST Management + POST S/U
	has_many :posts, inverse_of: :creator, foreign_key: "creator_id"
	has_many :postsupports, through: :object_actions, source: :object, source_type: "Post"

	
	# FB Activations	
	# MAKE MORE GENERAL
	has_many :facebook_activations
	
	# Functions
	def has_this_profile?(profile)
		profiles.include?(profile)
	end
	def has_this_facebook_activation?(facebook_activation)
		id == facebook_activation.creator.id
	end
	def has_pending_facebook_activations?(facebook)
		facebook.facebook_activations.collect{|fba| fba.creator}.include?(self)
	end
	def has_been_reported_for_facebook?(facebook)
		facebook.facebook_activations.select{|fba| fba.creator == self && fba.reported}.any?
	end
	def has_recent_facebook_activations?(facebook)
		facebook.facebook_activations.where("upadated_at > ?", 2.minutes.ago).collect{|fba| fba.creator}.include?(self)
	end
	def is_user?
		true
	end
	def is_potential_user?
		false
	end
	
	#DEVISE Soft Delete
	# instead of deleting, indicate the user requested a delete & timestamp it  
	def soft_delete  
		update_attribute(:deleted_at, Time.current)  
	end  

	# ensure user account is active  
	def active_for_authentication?  
		super && !deleted_at  
	end  

	# provide a custom message for a deleted account   
	def inactive_message   
		!deleted_at ? super : :deleted_account  
	end 
end	

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

	protected

	def after_resetting_password_path_for(resource)
		signed_in_root_path(resource)
	end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
   def edit
		@profile = Profile.new()
		super
   end

  # PUT /resource
   def update
		@profile = Profile.new()
		super
   end

  # DELETE /resource
  def destroy  
		resource.soft_delete
		Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)  
		set_flash_message :notice, :destroyed if is_flashing_format?  
		yield resource if block_given?  
		respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }  
  end  

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

	# The path used after sign up.
	def after_sign_up_path_for(resource)
		signed_in_root_path(resource)
	end

	#The path used after sign up for inactive accounts.
	def after_inactive_sign_up_path_for(resource)
		signed_in_root_path(resource)
	end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
	def new
		puts " les params que j ai reçus : "+params.inspect.to_s
		if params[:redirect_to].present?
			store_location_for(User, params[:redirect_to])    
		end
		super
	end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include UserObjectsModule
	def show
		@user = User.find(params[:id]) 
		@objects = objects_for_user(@user, current_user)
		
		@conversation = Conversation.new()
		@conversation.posts.build()
	end
		
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_add_profiles.html.erb
<h2>Add Profiles Partial ------------------------------------ ></h2>


FOR EXISTING PROFILES:
<%= form_for(profile, url: profiles_attach_to_user_path, html: { method: :post }) do |f| %>
	Select the Profile you want to make yours: <br/> 
	<%= select("profile", "global_id", available_profiles(current_user), {prompt: 'Select Profile'} ,:onchange => "this.form.submit()") %>
	<br/><br/>
<% end %>

<%= form_for(profile, url: profiles_attach_to_user_path, html: { method: :post }) do |f| %>
	Or enter a new profil or website...<br/>
	(example: www.facebook.com/bebeun92 or www.twitter.com/benoit81 or www.a_website.com ...) <br/>
	
	<%= text_field_tag 'profile[display]', nil, placeholder: 'Entire a new profile URL...' %>
	
	 <%= f.submit "Add this profile"%>
	<br/>
<% end %>


<br/>
<%= "You already asked for these profils: " if current_user.facebook_activations.where(creator: current_user, activated: false, reported: false).any? %>
<ul>
<% FacebookActivation.all.where(creator: current_user, activated: false, reported: false).each do |p|%>
	<li><%= p.facebook.description %><i><%= " (Already asked for this profil "+time_ago_in_words(p.updated_at)+" ago)" %></i>
	<%= button_to "Resend email",  url_for(controller: '/facebook_activations', action: 'resend', id: p), method: :post, form_class: "button_link" if p.updated_at < 2.minutes.ago && p.mailnumber <= 4 %>
	<% if p.mailnumber >= 2 &&  p.mailnumber <= 4 %>
		<br/><%= ( "You have already requested #{p.mailnumber} mails. Caution because you might hit a block. Still have a problem? Consult: ") %>
		<i><a href="https://www.facebook.com/help/224049364288051" target="blank" >FB instructions about mails @facebook.com</a></i>
	<% end %>
	<% if p.mailnumber == 5 %>
		<br/><%= ( "You have already requested #{p.mailnumber} mails. You can't send more. Still have a problem? Consult: ") %>
		<i><a href="https://www.facebook.com/help/224049364288051" target="blank" >FB instructions about mails @facebook.com</a></i>
	<% end %>
	<%= (button_to "Cancel Facebook request",  url_for(controller: '/facebook_activations', action: 'cancel', id: p), method: :delete, form_class: "button_link")  %>
	</li>
<% end %>



</ul>
<br/><br/>

		
<h2>---------------------------------------------------------------------------------------- </h2>

app/views/users/_edit_profiles.html.erb
<h2>Edit User Profiles Partial ------------------------------------ ></h2>
<ul>
	<% user.profiles.each do |ff| %>
		<li> 
			<%= ff.class.name+" : "+ff.description %> 
			<%= button_to "Remove", url_for(controller: '/profiles', action: 'detach_from_user' ), method: :post, data: { confirm: "Are you sure? This can not be undone" }, params: { "profile[global_id]" => get_profile_global_id(ff)}, form_class: "button_link" if user_signed_in? && user == current_user%>
		</li>
	<% end %>
</ul>
<h2>------------------------------------------------------------------------  </h2>

app/views/users/_show_supports.html.erb
<h2>Show User Supports and Unsupports Partial ------------------------------------ ></h2>
<%= (user_signed_in? && user != current_user) ? ("This is #{user.name} profile" ) : ("Dear #{user.name} , this is your profile") %> 


<% if user_signed_in? && user != current_user %> 
	<%= button_to "Support #{user.name}", url_for(controller: 'users', action: 'support', id: user.id ), method: :post, form_class: "button_link" if !user.supporters.include?(current_user)%>
	<%= button_to "Dis support #{user.name}", url_for(controller: 'users', action: 'remove_support', id: user.id ), method: :delete, form_class: "button_link"  if user.supporters.include?(current_user) %>
	<%= button_to "Dis unsupport #{user.name}", url_for(controller: 'users', action: 'remove_support', id: user.id ), method: :delete, form_class: "button_link"  if user.unsupporters.include?(current_user) %>
	<%= button_to "Unsupport #{user.name}", url_for(controller: 'users', action: 'unsupport', id: user.id ), method: :post, form_class: "button_link"  if !user.unsupporters.include?(current_user) %>
	
	
<% end %> 

<% if !user_signed_in? || user != current_user %> 
	<ul>
		<li><%= user.name %> is supported by:
			<% user.supporters.each do |x| %><%= render '/user_link', :xx => x %><% end %>		
		</li>
		<li><%= user.name %> is unsupported by:
			<% user.unsupporters.each do |x| %><%= render '/user_link', :xx => x %><% end %>
		</li>
		<li><%= user.name %> supports:
			<% user.supporting.each do |x| %><%= render '/user_link', :xx => x %><% end %>
		</li>
		<li><%= user.name %> unsupports:
			<% user.unsupporting.each do |x| %><%= render '/user_link', :xx => x %><% end %>
		</li>
	</ul>
<% end %> 

<% if user_signed_in? && user == current_user %> 
	<ul>
		<li>You support: 
			<% current_user.supporting.each do |x| %><%= render '/user_link', :xx => x %><% end %>
		</li>
		<li>You unsupport:
			<% current_user.unsupporting.each do |x| %><%= render '/user_link', :xx => x %><% end %>
		</li>
		<li>You are supported by : 
			<% current_user.supporters.each do |x| %><%= render '/user_link', :xx => x %><% end %>
		</li>
		<li>You are unsupported by :
			<% current_user.unsupporters.each do |x| %><%= render '/user_link', :xx => x %><% end %>			
		</li>
	</ul>
<% end %> 

<h2>---------------------------------------------------------------------------------------- </h2>

app/views/users/show.html.erb
<% provide(:title, "Show User") %>
<div id="modal-window" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
<div id="modal-window-post" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

<script language="javascript">
window.onload = function(e) {
        $("#modal-window").bind("hidden.bs.modal", function () {
			location.reload();
		});  
};
</script>

<h2>Welcome on <%= (@user == current_user) ? ("your") : (@user.name+"\'s")  %> wall...</h2></br>

<div class="container">
	<% @objects.each do |f| %>
	<div class="row">
		<div class="col-sm-10">
			<% if f.class.name == "Call" %>
					<%= render '/calls/show_wall', call: f %>
			<% end %>

			<% if f.class.name == "Post" %>
					<%= render '/posts/show_wall', :post => f %>
			<% end %> 

			<% if f.class.name == "ObjectAction"  %>
					<% if f.object_type == "Post" %><%= render '/posts/show_wall', post: f.object %><% end %>
					<% if f.object_type == "Call" %><%= render '/calls/show_wall', call: f.object %><% end %>
			<% end %>
			<br/>
		</div>
	</div>
	<% end %>
</div>

<% if user_signed_in? %> 
	<h2>Post Up Something...</h2>

	<%= form_for @conversation do |f| %>
		<%= render '/conversations/new', f: f, object: @conversation %>		
		<%= hidden_field_tag(:from, "User") %>
		<%= hidden_field_tag(:user, @user.id) %>
		<%= f.submit "Post Up"  %>
	<% end %>

<% end %> 